```{r data generation, echo = FALSE, results = "hide"}
## generamos datos aleatorios

alpha <- sample(c(0.01,0.05,0.1),1)

factor <- round(qnorm(1-alpha/2),2)
sigcuad <- round(runif(1,min=0.3,max=0.9),2)
#prob <- 1-2*pnorm(-1.96)

prob <- round(1-2*pnorm(-factor),4)

```

Question
========
Sean $X_i$ variables aleatorias independientes e idénticamente distribuídas, con $X_i\sim \mathcal N(\mu, \sigma^2)$, siendo $\sigma^2=`r sigcuad`$. Consideremos 
$$\overline X_n=\frac{1}{n}\sum_{i=1}^n X_i.$$
Calcular la siguiente probabilidad

$$\mathbb P\left(\overline {X}_n-`r factor`\sqrt{\frac{`r sigcuad`}{n}} <\mu <\overline {X}_n+`r factor`\sqrt{\frac{`r sigcuad`}{n}}\right)$$


Solution
========

Answerlist
----------

* Para resolver este ejercicio, recordemos que si las variables $X_i$ tienen distribución normal, el promedio también tiene distribución normal. Es más, conociendo las propiedades la esperanza y varianza para el promedio de variables iid, tenemos que 
$$\mathbb E(\overline X_n)=\mu\;\quad V(\overline X_n)=\frac{`r sigcuad`}{n}.$$
Tenemos entonces que 
$$\overline X_n\sim \mathcal N(\mu, \sigma^2/n).$$
Ahora bien, para calcular la probabilidad pedida, necesitamos estandarizar. Empezamos restando $\overline X_n$ en todos los términos para obtener que la probabilidad pedida coincide con
$$\mathbb P\left(-`r factor`\sqrt{\frac{`r sigcuad`}{n}} <\mu-\overline {X}_n <`r factor`\sqrt{\frac{`r sigcuad`}{n}}\right).$$
Ahora, multiplicamos por $-1$ (dando vuelta las desigualdades) y dividimos por $\sqrt{`r sigcuad`/n}$.
Concluímos entonces que la probabilidad pedida coincide con
$$\mathbb{P}\left(-`r factor`<\frac{\overline X_n-\mu}{\sqrt{`r sigcuad`/n}} <`r factor`\right)=\mathbb{P}\left(-`r factor`<Z<`r factor`\right)=\Phi(`r factor`)-\Phi(`r -factor`)$$
$$=\Phi(`r factor`)-[1-\Phi(`r factor`)]=2\Phi(`r factor`)-1=`r prob`$$



Meta-information
================
extype: num
exsolution: `r prob`
exname: IC1_nivel
extol: 0.01

